DB_NAME = "Eep_Tfg"
DB_PASSWORD = "andreidore"
DB_PORT = 3306
DB_HOST = "localhost"
DB_USER = "root"

CREACION_BBDD='CREATE DATABASE IF NOT EXISTS '+str(DB_NAME)+';'
CREACION_TABLA_USUARIOS='CREATE TABLE IF NOT EXISTS '+str(DB_NAME)+'.usuarios ( id INT AUTO_INCREMENT PRIMARY KEY, nombre_usuario VARCHAR(50) UNIQUE NOT NULL,contrasena VARCHAR(255) NOT NULL,nombre_completo VARCHAR(100) NOT NULL,email VARCHAR(100) NOT NULL,departamento VARCHAR(100) NOT NULL);'
CREACION_TABLA_ADMINISTRADORES='CREATE TABLE IF NOT EXISTS '+str(DB_NAME)+'.administradores ( id INT AUTO_INCREMENT PRIMARY KEY, nombre_usuario VARCHAR(50) UNIQUE NOT NULL,contrasena VARCHAR(255) NOT NULL,nombre_completo VARCHAR(100) NOT NULL,email VARCHAR(100) NOT NULL);'

