DB_NAME = "Eep_Tfg"
DB_PASSWORD = "andreidore"
DB_PORT = 3306
DB_HOST = "localhost"
DB_USER = "root"

CREACION_BBDD='CREATE DATABASE IF NOT EXISTS '+str(DB_NAME)+';'
CREACION_TABLA="CREATE TABLE IF NOT EXISTS {DB_NAME}.usuarios (id INT AUTO_INCREMENT PRIMARY KEY, nombre VARCHAR(255), email VARCHAR(255), password VARCHAR(255));"