DB_NAME = "Eep_Tfg"
DB_PASSWORD = "andreidore"
DB_PORT = 3306
DB_HOST = "localhost"
DB_USER = "root"

VENTANA_LOGIN_TITULO='Inicio de Sesión'
COLOR_VENTANA_FONDO='#F9F7F7'
IMAGEN_LOGO='src/img/logo_sek.png'
VENTANA_TAMANIO_LOGIN='300X200'

CREACION_BBDD='CREATE DATABASE IF NOT EXISTS '+str(DB_NAME)+';'
CREACION_TABLA_USUARIOS='CREATE TABLE IF NOT EXISTS '+str(DB_NAME)+'.usuarios ( id INT AUTO_INCREMENT PRIMARY KEY, nombre_usuario VARCHAR(50) UNIQUE NOT NULL,nombre_completo VARCHAR(100) NOT NULL,email VARCHAR(100) NOT NULL,departamento VARCHAR(100) NOT NULL);'
CREACION_TABLA_ADMINISTRADORES='CREATE TABLE IF NOT EXISTS '+str(DB_NAME)+'.administradores ( id INT AUTO_INCREMENT PRIMARY KEY, nombre_usuario VARCHAR(50) UNIQUE NOT NULL,contrasena VARCHAR(255) NOT NULL);'
CREACION_ADMIN='INSERT INTO '+str(DB_NAME)+'.administradores (nombre_usuario, contrasena) VALUES (%s,%s);'
CONSULTA_TODOS_ADMINISTRADORES='SELECT * FROM '+str(DB_NAME)+'.administradores;'
CREACION_USUARIO='INSERT INTO '+str(DB_NAME)+'.usuarios (nombre_usuario,nombre_completo,email,departamento) VALUES (%s,%s,%s,%s);'
CONSULTA_TODOS_USUARIOS='SELECT * FROM '+str(DB_NAME)+'.usuarios;'
